name: shinjin_pda_app
description: Shinjix Tax Pda App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  provider: ^4.1.1
  shrine_images: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  assets:
    - packages/shrine_images/0-0.jpg

